---@class BetterMacroIcons
---@field bundledSpellTerms table
local ns = select(2, ...)

-- Bundled baseline spell/racial search terms shipped with the addon. scan.lua's rebuildMerged
-- folds this under each account's live scans (deduped), so a fresh install has coverage out of
-- the box without anyone having to log every class/spec and race.
--
-- Generated by `/bmi export` (run it on a well-scanned account, then paste the copy-window
-- output over this file). Keyed by spec id (bySpec) and canonical race id (byRace); each value
-- is `{ [fileID] = " space delimited spell names " }`, the same shape scan.lua stores live.
ns.bundledSpellTerms = {
  bySpec = {},
  byRace = {},
}
